language: ruby
script:
  - bundle exec rspec
  - bundle exec rake export
deploy:
  # See https://github.com/travis-ci/travis-ci/issues/9312
  edge:
    branch: v1.8.47
  # Docs: https://docs.travis-ci.com/user/deployment/pages/
  provider: pages
  skip-cleanup: true
  keep-history: true
  # Personal access token for rubytoolbox-bot user, public_repo scope
  github-token: $GITHUB_TOKEN
  name: Ruby Toolbox Bot
  email: bot@ruby-toolbox.com
  local-dir: build
  verbose: true
  on:
    branch: master
