name: Logging
description: 
projects:
  - best_boy
  - cabin
  - clogger
  - fluentd
  - frogger
  - gelf
  - hatchet
  - httplog
  - justlogging-rails
  - log4r
  - logging
  - logging-rails
  - logging_assist
  - lograge
  - lumber
  - mongodb_logger
  - rake_bubbler
  - whoops
  - yell
